library PlasmidDetectedConcepts version '0.1.0'

valueset "Resistance Plasmid Mediated": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/PlasmidMediated'
valueset "AMR": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/AMR/'
valueset "antimicrobial resistant plasmid type": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/AMRplasmid/'
valueset "bacteria": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/bacteriaWGS/'
valueset "Detected Resistance Marker": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/ResistanceMarker/'
valueset "phenotypic antimicrobial drug susceptibility test": 'https://fhir.openconceptlab.org/orgs/cidgoh/ValueSet/drugSusceptibility/'